### ISSUE TITLE
Lista zakupów

### ISSUE THREAD

**Issue by BlackHabanero** [BlackHabanero/PKgr7Sieci#1]

**Comment by sonic9001** [comment]
EIA485
[Skrętka UTP 5E potrzeba 54m + zapas](https://www.tme.eu/pl/details/u_utp5e-scu/przewody-teleinformatyczne/technokabel/utp-kat-5e-4x2x0-5/) 
[konwerter RS485 -> TTL 5 sztuk -> 8,4zl/sztuka tu nalezy sie zastanowić jest sens kupować](https://botland.com.pl/interfejsy/7693-max485-transceiver-rs485-dip-5szt-5904422310738.html)

**Comment by Nivisnis** [comment]
Układy CAN do rozważenia 

Tranceivery: 
MCP2561-E/P [https://www.tme.eu/Document/772c262d0c66f712f1c1723a5571cf44/mcp2561_2.pdf](url)

**Comment by rann99** [comment]
Zaakceptowane wybory:
Opto:
Światłowód
https://www.tme.eu/pl/details/simplex-pe-pur/przewody-swiatlowodowe/lapp/28020001/
[Dokumentacja:](https://www.tme.eu/Document/6ee1764f40484254f5238d2ee9e6b51f/SIMPLEX-PE-PUR-PL.pdf)
Średnica włókna: 2.2mm
Długość trasy transmisji: 70m
Dopuszczalny promień gięcia: ≥10 x średnica zewnętrzna
Dopuszczalna siła rozciągająca:
Połączenie nieruchome: 100 N
Krótkotrwale: 600 N

CAN:

RS485:

Radio:

**Comment by BlackHabanero** [comment]
Closing commit: https://github.com/BlackHabanero/PKgr7Sieci/commit/351e55258a6647ca6ecbd997b0785359b9e9f034
[Link: Lista zakupów - Sieć w Sali 305.pdf](https://github.com/BlackHabanero/PKgr7Sieci/blob/351e55258a6647ca6ecbd997b0785359b9e9f034/Dokumentacja/Kosztorys/Lista%20zakup%C3%B3w%20-%20Sie%C4%87%20w%20Sali%20305.pdf)
